### ISSUE TITLE
iOS UI

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/groceristar#108]
# Description/Steps to reproduce
https://app.buymeapie.com/
![image](https://user-images.githubusercontent.com/1469198/30236100-5b90efc6-951b-11e7-90b1-5c4d393e9d45.png)
![image](https://user-images.githubusercontent.com/1469198/30236103-60924b00-951b-11e7-9eda-4e99b34b3855.png)
![image](https://user-images.githubusercontent.com/1469198/30236110-7b013a28-951b-11e7-82e8-ff028047b1ca.png)

# Expected result

# Additional information

**Comment by sugus25** [comment]
Thank you
