### ISSUE TITLE
Setting up a copy of GS on localhost

### ISSUE THREAD

**Issue by yxie66** [GroceriStar/groceristar#218]
# Description/Steps to reproduce

I may set up a copy of GS (pull from github) on my localhost in the future, which enables me to test it on my local computer.

@xy1994 

- [x] First of all you'll need to fork my repo. 
- [x] Then you'll need to read an article about git-flow and setup a nice process in your repo(a little catch there).

This is a not clean Loopback, as you can find. Some things may look very tricky.
Most important things: provider.json, where we place a credentials of test Facebook application(will work on your local well).
Next important thing is link to database. As we're using heroku+mLab for mongoDB, you can leave this database as is. But later it'll be better to create your own heroku app, attach mLab addon and change database link. BUT, don't forget to ignore file, with database, because if you'll push it on my instance - it may cause some troubles.

- [x] Create your own app with mLab addon

1) Buzz me, when you'll setup a local version without changes in db credentials. I want to take a look
2) Buzz me, when you'll update settings to your environment(db link only for now) and commit changes and make a PR to non-master branch.

- [ ] implement git-flow

- [ ] commit with ignore 

- [ ] create PR as mentioned

Then, when you'll get your clean database I'll show you how to import data for UltimateGrocery list tempalate.

# Expected result

# Additional information

**Comment by atherdon** [comment]
did you do npm init on your Lenovo PC? :)

**Comment by yxie66** [comment]
Yes. How do you know?

**Comment by atherdon** [comment]
I'm watching you

**Comment by atherdon** [comment]
https://sentry.io/atherdon/grocery/issues/389041329/

See server.js

**Comment by atherdon** [comment]
@xy1994 if it went bad - let's try to fork again

**Comment by atherdon** [comment]
Let's go step by step, @xy1994 

1. fork
2. `npm init`
3. to run `npm run watch`
4. browser `localhost:3000`
Buzz me, @xy1994 if this not help.
Then I'll try to re-run it on my side.

**Comment by atherdon** [comment]
https://sentry.io/atherdon/grocery/issues/389083776/

**Comment by atherdon** [comment]
Hold on @xy1994, put here information about your node version and npm version

**Comment by yxie66** [comment]
Hello Arthur,

1. Two links you provided requires user name and password to login.

2. Faced an error when npm run watch and trying to fix

"async function something(next) {
  ^^^^^^^^
SyntaxError: Unexpected token function"

in the 12th line of server/like-middleware-helper.js

My node version is 6.10.2 while npm is 5.5.1

**Comment by atherdon** [comment]
Good @xy1994 I'll add you to this helper software.
Ok, we got the main trouble:
![image](https://user-images.githubusercontent.com/1469198/31922438-8e3688d4-b87d-11e7-83d6-92f48e703e0d.png)
![image](https://user-images.githubusercontent.com/1469198/31922446-959f7e96-b87d-11e7-95ad-ed482ac4f640.png)
fully remove your node and npm instance and install again(not upgrade)

**Comment by atherdon** [comment]
Btw, i've made this issues available for public. But they paste my links.
So here s your PC data: 
https://sentry.io/share/issue/1fbd6e07065840c9b788ab2948dbe140/

https://sentry.io/share/issue/df98338a20c94c54b66b4315d1324395/

Looks like this integration can save us a bit of time

**Comment by yxie66** [comment]
Works now! @atherdon  Appreciate your help!

**Comment by atherdon** [comment]
You welcome. Btw, As U know to install on local machine :
- [ ] you can submit a PR with updates to readme file with step-by-step plan that we find out here

**Comment by yxie66** [comment]
I have fixed two minor typo in department.js and ingredient.js, removing the extra ",". At present when I run "git flow init", it says "working tree contains unstaged changes". It may be because of I have changed the file.

**Comment by atherdon** [comment]
git flow its a term, not a cmd command.
it's just an approach for organizing branches and commits for better
working together

**Comment by yxie66** [comment]
Got it. I have created a test PR.

**Comment by atherdon** [comment]
2 notes: you push into master branch, and your commit message don't
specify what exactly you did :slightly_smiling_face:

**Comment by yxie66** [comment]
Sorry about that. What branch do you expect me to push into?

**Comment by atherdon** [comment]
No problem, I know that this will be happen :slightly_smiling_face:
At which branch you need to push you'll find out in "git-flow" article, get
back and re-read it. Don't worry - it's ok. you're doing better than me
when i start to use git. I broke 7 repos in a row 😂

P.s. haha. autocomplete is try to made mess with my reply "it's ok. you're
don't better than me"
I submit changes. at this time i'll approve PR to master(after changes)

**Comment by yxie66** [comment]
thx so much for encourage! 
Having submitted two commits in PR.

**Comment by atherdon** [comment]
@xy1994 I'm still here, so if you have your questions - ask them

**Comment by yxie66** [comment]
Hello Arthur, glad to see you! Have you finished your moving?

**Comment by atherdon** [comment]
Nope i'm still in my current place

**Comment by atherdon** [comment]
@xy1994 Hi, I'm looking for any updates.

**Comment by yxie66** [comment]
Hello Arthur, I am here! Sorry for being busy. I am researching the GS and assigned tasks. How about updating the readme first about several issues?

**Comment by atherdon** [comment]
Hi Yi, thank you for your reply!
I'm pretty ok with updating readme.
did you know what to do, or you need my assist?
Arthur

**Comment by yxie66** [comment]
Thank you! I am going to look at assigned tasks and working on the version 1.0.1 -- the most updated version running on my local machine. When I need clarification I will ask you. For instance -- in https://github.com/atherdon/groceristar/issues/251, where do you expect us to have a wrapper?

**Comment by atherdon** [comment]
@xy1994 it'll will be also a good idea to run similar merge between master
and develop.
you did it before, so it wouldn't be a problem.
after this merge we'll be able to fully migrate to git-flow implementation,
'cause i'm pretty sure that i'll not be able to work on GS for a some time.
Will create a task for you.

we have 2 bugs on my latest 1.2 release. but i plan to solve it with help
of my friends.

Btw, it'll be better to ask related questions in related tasks. so please
move your question to that task and i'll gladly reply to it.

Small info, i start to participate in product hunt global hackaton. dont
have much news, but is a pretty interesting and fresh experience(also
stressful, but fun)

**Comment by atherdon** [comment]
hold on for a 10 minutes, i'll create a nice description for you what to
do next

**Comment by yxie66** [comment]
That would be awesome! When will be the hackaton? It sounds very cool.

**Comment by atherdon** [comment]
it's going right now. it's online and it's huge... and i made some
progress in first week. not very happy with it, but i get a nice
experience. also i'm going like a blind 1 leg man, without any experience
with technologies that i try to use :slightly_smiling_face:

**Comment by atherdon** [comment]
please open this task. for a few weeks it'll be a main thing to read:
https://github.com/atherdon/groceristar/issues/291
