### ISSUE TITLE
FacebookAuthorizationError on local machine

### ISSUE THREAD

**Issue by yxie66** [GroceriStar/groceristar#223]
# Description/Steps to reproduce

Trying to fix it.

Screen from Test app:
![facebook developers](https://user-images.githubusercontent.com/1469198/31970903-60b2d232-b922-11e7-917e-38ba9a17301c.png)

- [x] Add information to readme tutorial, when will be solved

# Expected result

# Additional information

**Comment by yxie66** [comment]
Error: Can't Load URL: The domain of this URL isn't included in the app's domains. To be able to load this URL, add all domains and subdomains of your app to the App Domains field in your app settings.

Steps having done:

1. Create a developer account in developers.facebook.com/
2. Change the clientID/clientSecret in providers.json
3. Settings- Site URL - http://localhost:3000/
4. Facebook Login - Valid OAuth redirect URIs - http://localhost:3000/

Going to fix it.

**Comment by atherdon** [comment]
@xy1994 
Just googled this like "facebook developers Error: Can't Load URL"

https://wp-native-articles.com/blog/news/how-to-fix-facebook-apps-error-cant-load-url-domain-url-isnt-included-apps-domains/

**Comment by yxie66** [comment]
Fixed! @atherdon Thank you for the helpful link. I found some more complex approaches on stackoverflow, but they didn't work.

I will add details to the readme file and post a PR later.
