### ISSUE TITLE
Make similar megre between master and develop branches

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/groceristar#289]
# Description/Steps to reproduce

_it'll will be also a good idea to run similar merge between master and develop.
you did it before, so it wouldn't be a problem.
after this merge we'll be able to fully migrate to git-flow implementation, 'cause i'm pretty sure that i'll not be able to work on GS for a some time._

**Q** I think I have merged the master and develop branches before, do you expect me to complete it on the 1.1 version? If so, I could replace my repo with the 1.1 version. What's more, do you expect these tasks completed on my repo or yours, or both?

**A**
Yes, I want you to an update you working version with my latest updates. You need to run the same approach that you did on the previous merge.
Btw, i think it'll be better, to create another with develop branch in other local folder and run merge from that destination. it's still not the best way... BUT, if i forget something, and my changes will raise commits - it'll be better to have your 1.1 working version that we've set up before.

# Expected result

# Additional information

**Comment by atherdon** [comment]
@xy1994  updated

**Comment by yxie66** [comment]
Got it, thank you. I will have the 1.1 version -- most updated and working version on my side so far.

**Comment by atherdon** [comment]
keep it just for a few days, while we'll not be sure that we're solid with
a new updates

**Comment by atherdon** [comment]
Do you make a PR or push to develop branch? I mean if i want to start to work on develop branch - i can just checkout and all will work, right?

**Comment by yxie66** [comment]
Yes, but it's on my own remote branches currently, not on your branches yet. I think you may need to develop in 1.2 version on your branches, and I can keep the 1.1 one on my side.

**Comment by atherdon** [comment]
Hmm, ok I got it, but i wanted you to start to work on 1.2 too - because
it's more up to date

**Comment by atherdon** [comment]
I don't plan to develop GS in a next few weeks myself. i think i can do
more by managing tasks

**Comment by yxie66** [comment]
Ok. So should I be updated with the "upstream"?

**Comment by atherdon** [comment]
in order to make "coding" tasks - yes. i'm ok if you'll keep 1.1 You can
have 2 separated folders: A(folder with cloned repository with 1.1version
and your local setup), B(folder with latest changes, with release 1.2)

**Comment by yxie66** [comment]
Thank you, got it. Is it a good idea to keep updated of both my master and develop with yours?

**Comment by atherdon** [comment]
not sure what do you mean. explain please

**Comment by yxie66** [comment]
Sorry, I intended to mean that making my master/develop branches updated as your master/develop -- I think they keep the updated 1.2 version. Then I can work on it

**Comment by atherdon** [comment]
you can keep only develop, if you're develop will be like mine - at this
moment you'll have troubles with connection to db - this is why we
extending functionality - so anyone can grab a copy and run their own
instance. so it's like dual question. you need to have my main changes on
your side, but you also need to configure workflow to keep you credentials
separated

**Comment by atherdon** [comment]
to be short - in order to make code changes - you must have latest
updates,

**Comment by yxie66** [comment]
Got it, so I may update with the upstream develop, change the db credential to make it working, then update the readme issues. Does I understand right?

**Comment by atherdon** [comment]
yep, it's right, but before updating creds - make a pr in order to have
1.2 code changes in our(my) develop branch. because when you'll update
creds - you'll need to configure gitignore - to keep your creds only at
your place and don't replace mine

**Comment by atherdon** [comment]
configuring gitignore is one of our next tasks

**Comment by atherdon** [comment]
#290 is responsible for gitignore

**Comment by yxie66** [comment]
Thank you. I'll keep you updated once progress is made.
