### ISSUE TITLE
Setting up a copy of GS on localhost (clear)

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/groceristar#290]
# Description/Steps to reproduce

it's a duplicate of issue #218. I want to make things more clear.

You are pretty close to finish this issue #218. We have unchecked checkboxes. So i'll duplicate them to this issue because that issue has a lot of distractions. I'm adding important notes from that issue to make things better

_Most important things: provider.json, where we place a credentials of test Facebook application(will work on your local well).
Next important thing is link to database. As we're using heroku+mLab for mongoDB, you can leave this database as is. But later it'll be better to create your own heroku app, attach mLab addon and change database link. BUT, don't forget to ignore file, with database, because if you'll push it on my instance - it may cause some troubles._

- [ ]  implement git-flow **When all next commits will go to devel**

- [ ] update settings to your environment(db link only for now) and commit changes and make a PR to non-master branch. **You try it before, but failed because of complexity of heroku+mlab integration.** You need:
 
     0. checkout a new branch from devel
     1. to create another new heroku app

     2. add clean mlab addon 

     3. go to settings and copy variable to a db link.

     4. run import to your new database and make sure that all is working well and your local copy can be launched and viewable from your browser.

     5. you need to find out how gitignore works. you need to prevent commits with information about your local settings: db links, facebook credentials. this is important for future security and for making our project production ready.
    6. commit with ignore
    7. create PR to develop branch

# Expected result

# Additional information

**Comment by yxie66** [comment]
@atherdon Hello Arthur, sorry for annoying, I am trying on heroku+mlab integration. All seem fine, but the npm run import doesn't work. Could I discuss with you?

**Comment by atherdon** [comment]
sure, give me some time - just woke up

**Comment by atherdon** [comment]
Hold on, you flowing me with errors :)

**Comment by atherdon** [comment]
https://sentry.io/share/issue/1759b08d052548588b811dc4bbb2e37f/
https://sentry.io/share/issue/3cfce39a714646518e96a95dca007b8f/
https://sentry.io/share/issue/5e289098c20848a1b1b78e35ef9ae718/
https://sentry.io/share/issue/bff688f558e7465e8fdc2b5a1105a41c/

this is errors that you generating. Let's try to solve them

**Comment by atherdon** [comment]
Btw, why did you jump to this task? Are all previous tasks on my list is completed?

**Comment by atherdon** [comment]
1 issue is similar to my previous issues: it's my bug and looks like merge not going very well. How to fix: you need to move **import** folder from master branch to yours and run import again.

Try it and then we'll discuss our plan

**Comment by yxie66** [comment]
The thing I want to do -- heroku+mlab integration in my local machine, as you put in this issue.
My version --- same as the version in your develop branch. That's say, keep both develop same.
My work:
1. run it on local machine -- works.
2. change the db with mine -- works.
3. change the db link in datasource.json and datasource.production.json with mine.
4. npm run migrate -- works
5. npm run import -- doesn't work : empty lines, can't import
6. localhost: 500 Cannot read property 'id' of undefined

**Comment by yxie66** [comment]
Ok, I'll move the import first.

**Comment by atherdon** [comment]
I think we have more deep issue here. but let's find out if im right with import

**Comment by yxie66** [comment]
I think it has been resolved, by replacing the import. Thank you so much! So I have reproduced on my local machine using both my own fb account and mlab. Working code will be on github soon.

**Comment by atherdon** [comment]
Hold on a second :)

**Comment by atherdon** [comment]
I think our mergin process not going very well. we can try push as we do before, but maybe it's a good time to pause and think about a simple(not cool, really) but with a little headache way. 

You know, we're trying to accomplish a git-flow in GS. And right now only few your changes are pushed to **develop branch**. I think it's about 4 commits. 
What I propose: 
1 way: 
a) you add pull request with your 4 commits to a master branch
b) then after my approve you'll checkout a brand-new develop branch - and we'll know that all things are up to date.

2) way: 
a) you checkout master first to a brand-new develop branch
b) add similar changes to your new branch
c) PR with publishin a new branch
d) later merge your changes with master branch (main reason: I want an updated Readme in master)

please tell me what do you think? This will be really easy to do rather then try to understand what is going wrong

**Comment by yxie66** [comment]
How do you think? I think the way 1 would be clear, while way 2 is also good, but my branch is not 1.2 at present. By the way, how could I submit PR while we have different fb and mlab in our develop?

**Comment by atherdon** [comment]
let's try, as we think that we'll change develop branch soon. also i'm curious about what you've did

**Comment by atherdon** [comment]
Btw, I'm ok with choosing Way1. It'll make a lot of things better. And soon you'll be happy - because when this setup hell will be finished - other things will go really easy!

**Comment by yxie66** [comment]
I came up with "There isn’t anything to compare. atherdon:master and xy1994:develop are entirely different commit histories." when I was trying to make a PR.

**Comment by atherdon** [comment]
try PR develop to develop

**Comment by yxie66** [comment]
Same issue

**Comment by atherdon** [comment]
hmm. can you add your changes to commits to your fork repo? i mean we'll just copy-paste them later

**Comment by atherdon** [comment]
it's like we'll keep your current changes, but will get back to them later.
also push it to your github repo - for easy access

**Comment by atherdon** [comment]
And then let's try Way1

**Comment by yxie66** [comment]
The change is already on my develop branch. It is the updated version.

**Comment by atherdon** [comment]
good. then leave it as is. Please check latest notifications - I add some updates in your main task and add some clarification to other

**Comment by yxie66** [comment]
I have seen it. As I only updated the db and mlab, not readme yet, I want to make PR about readme to your develop, and how could I do it? I am quite sure our develop branches share most of code -- but not commit history

**Comment by atherdon** [comment]
can you show me your changes at readme? i mean share with me commit to your forked repo with changes

**Comment by yxie66** [comment]
In the most recent commit on develop, I only replaced the import with the one on your master and change the mlab link. I think you may see it in my repo

**Comment by atherdon** [comment]
yes, maybe I can :) but i want you to share link at github with your commit related to this update

**Comment by yxie66** [comment]
https://github.com/xy1994/groceristar/commit/110a4a6b597cfa3243c560b328160d2c1a8a0103

May be it's the one you want?

**Comment by atherdon** [comment]
no, its related to import folder update

**Comment by atherdon** [comment]
i think previous

**Comment by yxie66** [comment]
Actually this commit includes the updating of my own mlab link. The other change of my own db could be in the previous commit.

**Comment by atherdon** [comment]
Ohh, my fault!

**Comment by atherdon** [comment]
my brain is still boot up.

**Comment by yxie66** [comment]
no problem at all!

**Comment by atherdon** [comment]
gotcha. ok, let's keep this commit and start from scratch with way1

**Comment by yxie66** [comment]
Then where can I create a PR?

**Comment by atherdon** [comment]
i think i don't get your question. can you explain

**Comment by yxie66** [comment]
Way1: 
a) you add pull request with your 4 commits to a master branch
b) then after my approve you'll checkout a brand-new develop branch - and we'll know that all things are up to date.

The issue here is that what I mentioned before -- there is mutual commit history between my develop and your master, then PR can't be created.

**Comment by atherdon** [comment]
Gotcha

**Comment by atherdon** [comment]
Btw, with all this setup hell - you are good with explaining. i see your growth!

This is a step by step:
you'll leave your 2 local folders as is
create a new folder and fetch my **master** branch
add changes to that branch
then create a PR with changes from your **master** branch to my **master** branch
tell me is this clear

**Comment by yxie66** [comment]
Thank you very much!
clone your master in a new folder -- fetch it -- make changes on local machine --- commit on my own master -- create a PR --- is it right?

**Comment by atherdon** [comment]
i think yes, let's try

**Comment by atherdon** [comment]
i got your issue.
Btw, i think you cheated - you didn't create a new folder:
**E:\2017fall\project\groceristar\groceristar - develop - 1.0.2**
https://sentry.io/share/issue/bb716dcb608c4eba8b30bc23daa9fe9c/

not sure why you got this issue. are you trying to run project in browser?

**Comment by yxie66** [comment]
I was making same changes to the new folder and trying whether it can run successfully on the local machine. Then I can commit on my own master.

**Comment by atherdon** [comment]
i think right now you don't need to start a server from your cmd.
i mean first changes is just open commit in browser - move changes to files - commit to your branch
then create a PR.
i mean this will save your time

**Comment by atherdon** [comment]
Btw, this issue at index.js line №510

**Comment by yxie66** [comment]
The issue is that I can't create a PR. The thing i have done is cloning the code on your master and making changes. The successful changes are made on your code on develop --- maybe that's the issue?

**Comment by atherdon** [comment]
i don't know :0 and don't want to know.
let's try a simple test.
can you open this file in browser - click **edit** and then add some changes and push changes to my repo?
https://github.com/atherdon/groceristar/blob/master/README.md

all in browser, not your editor

**Comment by yxie66** [comment]
Can you see the change?

**Comment by atherdon** [comment]
yep

**Comment by yxie66** [comment]
didn't know we can directly make the change on browser...

**Comment by atherdon** [comment]
it's not a best way, it can show you that this is not a git problem. just that branch is broken and we leave it

**Comment by yxie66** [comment]
How I created my current develop branch : clone your branch -- creating a new folder -- commit on my own develop -- making changes -- copy and paste import folder

**Comment by atherdon** [comment]
hold on, let's go step by step and we'll solve this shit :)
did you see this my comment: https://github.com/atherdon/groceristar/issues/297#issuecomment-343626940
