### ISSUE TITLE
JS beginner tutorials

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/groceristar#355]
# Description/Steps to reproduce

hi @elansari100,
So first step is to find 5 tutorials and send links here. I want to review it before you'll start.
or we can just find a paid tutorials if you ok with this way too

# Expected result

# Additional information

**Comment by elansari100** [comment]
https://www.tarleton.edu/COSTWEB/computerscience/documents/CS%20230%20Documents/Articles/JavaScript%20Tutorial.pdf
http://chuckeasttom.com/LearnJavaScriptProg.pdf
https://www.tutorialspoint.com/nodejs/nodejs_tutorial.pdf
https://nodejs.org/api/debugger.html
https://www.youtube.com/watch?v=-u-j7uqU7sI&list=PL6gx4Cwl9DGBMdkKFn3HasZnnAqVjzHn_

**Comment by atherdon** [comment]
First and second books are ok in order that you read them completly. they have some parts, related to display at browsers - we don't need it, like - `document.write()` stuff. But default part is good.

Nodejs tutorial is more about using javascript with nodejs server - but i think we need to fresh your memory with only-js first.

Youtube video is nice - but long :) Still - it's clear and give a lot of details. you'll be able to use it when we complete js basics.
Ok, I like what did you find.

Btw, this is links from my side - it's up to you what to use. Most clear and up-to-date information that i use is: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Iterators_and_Generators 
Start from the beginning and when you'll complete it - you'll be ready with latest trends knowledge.
also, i enjoy how us students use courses from https://www.freecodecamp.org/

They have different challenges, for different skills. and it's like a portfolio when you have a long list of completed challenges/courses at freecodecamp - amazing product!
@elansari100

**Comment by atherdon** [comment]
@elansari100 if you'll want to take a break, or switch later to a some other task - i think i can use your SQL skills too. we're using mongo, but it's all about relation tables, right? table + table, id to id, etc. so buzz me then and i'll create another task. it'll be later, for sure - just want to let you know

**Comment by elansari100** [comment]
I like the links you sent me, let's focus on js basics for now, then we can
go toward different tasks. I'll be done with this by Monday, so I'll wait
for something else from you by Monday night.

Thanks

2017-12-23 16:29 GMT-05:00 Arthur Tkachenko <notifications@github.com>:

**Comment by atherdon** [comment]
Omg - you fast! i have something for you - so don't worry. i'm also not
pausing on holidays - so i'll be in the loop with you.

**Comment by atherdon** [comment]
How things going, @elansari100 ? do you need my help or advice? feel free to ask

**Comment by atherdon** [comment]
`mongodb://heroku_gd1450xc:p8pd65v4k769jfgeauos1jdqpr@ds133557.mlab.com:33557/heroku_gd1450xc` second link

**Comment by atherdon** [comment]
#385

**Comment by atherdon** [comment]
just follow up you
