### ISSUE TITLE
templates, part#1

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/groceristar#418]
# Description/Steps to reproduce
all information read here #417

1. http://www.allyou.com/food/one-list-five-meals/meal-planner-hearty-dish
2. https://www.popsugar.com.au/fitness/Vegan-Dinner-Meal-Plan-36504112
3. https://www.vegan-nutritionista.com/first-vegan-grocery-list.html
4. http://www.healthytippingpoint.com/2012/07/our-vegetarian-gluten-free-grocery-list.html
5. https://laurenrabadi.com/2017/10/11/the-ultimate-keto-diet-beginners-guide-grocery-list/
6. http://www.eatingwell.com/article/126017/7-day-budget-meal-plan-shopping-list/
7. http://frugalinsa.com/basic-grocery-list/
8. https://www.self.com/story/heres-how-i-spent-40-at-trader-joes-and-ate-healthy-for-a-week
9. http://www.health.com/health/article/0,,20409813,00.html
10. http://thefinancialdiet.com/50-grocery-list-recipes-first-gluten-free-week/
11. http://www.wholefoodsmarket.com/blog/gluten-free-shopping-guide-against-all-grain
12. http://www.eatright.org/resource/health/diseases-and-conditions/celiac-disease/the-gluten-free-diet-building-the-grocery-list
13. https://www.veganmainstream.com/2010/09/02/eating-vegan-on-21-00-a-week-the-food-stamp-budget/

# Expected result

# Additional information

**Comment by atherdon** [comment]
14. http://www.healthytippingpoint.com/2011/02/eat-in-challenge-shopping-cart-trader-joes.html

**Comment by jaygeet** [comment]
sublink "page not found". http://www.allyou.com/static/pdf/shopping-list-wk21.pdf from  http://www.allyou.com/food/one-list-five-meals/meal-planner-hearty-dish
