### ISSUE TITLE
intro Niranjhana. first tasks

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/groceristar#424]
# Description/Steps to reproduce

1. setup task for local setup
2. #228 
3. #202 
4. #194 

# Expected result

# Additional information

**Comment by atherdon** [comment]
@atherdon explain #194 task

**Comment by atherdon** [comment]
just follow you up

**Comment by ninayar** [comment]
Hey,

I am really sorry. But I couldn’t get the local setup done and so I didn’t proceed after that. Do you have any document other than the page on GitHub with the instructions?

-- 
Niranjhana Nayar,
Graduate Assistant | ECE Department
MS Computer Science
New York University

**Comment by atherdon** [comment]
@ninayar it's ok. I think starting from that task is require a lot of knowledge of current setup. and not only you was stuck and decided to pause. 

For sure i have install tutorial, but...
I find an another way to continue to work together and it'll be more easiest way to start for non-experienced software engineers.
if you interested - i'll share to you more details.
