### ISSUE TITLE
Intro to groceristar

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/groceristar#440]
# Description/Steps to reproduce
Exec person: Harigovind
Contact: https://www.facebook.com/harig1999

Video samples: https://github.com/atherdon/artics/tree/master/stuff/videos
maybe can help you

Check list:

- [ ] we must have a good step-by-step guide how to work with GS.
- [x] we must attach some screenshots - please attach a few samples.
- [ ] we must place link to our website.
- [ ] we also must finish our updated homepage(so it's blocker)
- [ ] we must have at least 4 minutes of reading
- [ ] we must show how product can be beneficial for our users.
- [ ] we must notice that its open-sourced, so anyone who want to contribute - is welcome.
- [ ] it'll be cool to explain our roadmap. can be a simple, but will give an understanding that this is just a first version and more and more features will come soon.
- [ ] we must ask for claps, cause it's important.
- [ ] we must have a 'juicy' english and it must be a little fun

# Expected result
Text in English, that i'll post on Medium.

# Additional information

**Comment by HarigovindG** [comment]
Things I will need:

- [x] 1) Screenshots of Groceriestar 
- [x] 2) Link to complete working groceristar website 
- [ ] 3) Written content about the working of Groceriestar and the road map. 

I feel that these things will help me put out a better researched article that does justice to your idea.

**Comment by atherdon** [comment]
for sure, start to work on it.
Please note that we'll have revisions, so what you'll done at first time - will have corrections
@HarigovindG

**Comment by HarigovindG** [comment]
Okay, so without the written content about your idea and the road map, I won't be able to go into detail about that.
Without the link and the screen shots, I can't  go very much into detail.

**Comment by HarigovindG** [comment]
So with what I have right now, I can start working on a basic introduction article that goes into detail about groceristar from what you've told me till yet. Is that okay?

**Comment by HarigovindG** [comment]
So with what I have right now, I can start working on a basic introduction article that goes into detail about groceristar from what you've told me till yet. Is that okay?

**Comment by atherdon** [comment]
link: http://groceristar.herokuapp.com/

yep. this was the main idea. right now you on your own - just exploring the project as a user.

**Comment by atherdon** [comment]
@HarigovindG  Please check this folder for screenshots. https://github.com/atherdon/groceristar/tree/master/documentation
Wiki page: https://github.com/atherdon/groceristar/wiki/Screenshots
If you want - i can create a small explanation for each of this image for you.

**Comment by atherdon** [comment]
@HarigovindG check some info here: https://github.com/atherdon/artics/blob/master/Not%20finished/gs-vision-maybe

**Comment by atherdon** [comment]
hi @HarigovindG, just follow you up in order to check how things going

**Comment by atherdon** [comment]
If you have any questions - don't hesitate to ask.

**Comment by HarigovindG** [comment]
I was working on something but my computer got damaged. That's why I
couldn't put put good stuff. Gimme a little time, as I got some exams and
stuff also going. Is that fine?

**Comment by atherdon** [comment]
ok, take your time, not pushing, just want to know about the progress.
thanks!

**Comment by atherdon** [comment]
we have some progress on this part of article, so before continue to work on this article buzz me - i'll share more details with you

**Comment by HarigovindG** [comment]
Hi Arthur, I never got the data and screenshots you said you'll give. And
my computer got damaged. Either way. Send me the data and screenshots and
I'll give you the article ASAP.

**Comment by atherdon** [comment]
i think i posted screenshots in February - you can check our chat at the top.
Btw, i moved my repo from my account into company account - so yeah - that link looks like broken
again: https://github.com/GroceriStar/groceristar/wiki/Screenshots
video that shows how the project looks at the current stage: https://vimeo.com/260263675

our first arctile related to intro was published, so you'll need to create a second version
please take a look: https://medium.com/groceristar/why-having-an-online-grocery-shopping-list-is-a-smart-idea-5684221c6939

Please also check 2 articles below and tell me is it enough data for you to proceed further.
https://github.com/atherdon/artics/blob/master/Not%20finished/PUBLISHEDgs-vision-maybe.md
https://github.com/atherdon/artics/blob/master/recipes%20about/grocery-list-basic-functionality

still, don't want to push you. just want to share with you that we did a first intro article, so you'll not spend your time on the same thing. and remember that your pc was damaged. sorry to hear that. this is why i'm using online storages in order to keep it in save.

**Comment by HarigovindG** [comment]
What do you have in mind for the second article?

And I don't think I got the screenshots then.

**Comment by atherdon** [comment]
just create an intro to groceristar content too. and avoid intersections with that article.

check images below and tell me is it ok for you
![groceristar herokuapp com](https://user-images.githubusercontent.com/1469198/38732912-b04289f0-3f28-11e8-9e9c-07e1a20b5385.png)
![groceristar herokuapp com auth account _ _](https://user-images.githubusercontent.com/1469198/38732914-b066cd38-3f28-11e8-87ef-635a002fcfe8.png)
![groceristar herokuapp com auth account _ _ 1](https://user-images.githubusercontent.com/1469198/38732915-b086d6be-3f28-11e8-8f9b-b18b1fa1ec43.png)
![groceristar herokuapp com departments show 5a6fb00ef3909e0012274dab](https://user-images.githubusercontent.com/1469198/38732916-b0a55bac-3f28-11e8-8246-ea40e602e463.png)
![groceristar herokuapp com departments show 5a6fb00ef3909e0012274dab 1](https://user-images.githubusercontent.com/1469198/38732917-b0c3ad5a-3f28-11e8-9f51-d866bfbb0dbb.png)
![groceristar herokuapp com view grocery 5a6fb00ef3909e0012274dab](https://user-images.githubusercontent.com/1469198/38732918-b0e24de6-3f28-11e8-9898-b6057839f5f6.png)
![groceristar herokuapp com view ultimategrocery](https://user-images.githubusercontent.com/1469198/38732920-b100b5c4-3f28-11e8-826e-064f4bb9ca78.png)
![groceristar herokuapp com view ultimategrocery 1](https://user-images.githubusercontent.com/1469198/38732921-b121339e-3f28-11e8-8b88-348a0c2a6cab.png)
![shopping list 5a6fb00ef3909e0012274dab](https://user-images.githubusercontent.com/1469198/38732922-b13fa4c8-3f28-11e8-8d13-5f06c63d3610.png)
![shopping list 5a6fb00ef3909e0012274dab 1](https://user-images.githubusercontent.com/1469198/38732923-b15deb40-3f28-11e8-9224-e82a8d3d03a9.png)
![shopping list 59f1695cd534650012ae0ee7](https://user-images.githubusercontent.com/1469198/38732925-b17b767e-3f28-11e8-9879-30f08c85fa9c.png)
![shopping list 59f1695cd534650012ae0ee7 1](https://user-images.githubusercontent.com/1469198/38732928-b1988bd8-3f28-11e8-8261-f4b7b8595f0e.png)
